# Generated by Django 3.0.7 on 2020-06-18 07:22

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200618_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='distributor',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='profiles/distributor'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='profiles/farmer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(default='avatar.png', upload_to='profiles/manufacturer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
